### ISSUE TITLE
cant find module yeoman-environment

### ISSUE THREAD

**Issue by guruward** [mwaylabs/generator-m-ionic#404]
$ yo m-ionic
module.js:327
    throw err;
    ^

Error: Cannot find module 'yeoman-environment'
    at Function.Module._resolveFilename (module.js:325:15)

**Comment by gruppjo** [comment]
Hi @guruward, looks like there was a problem with npm during install (disconnect or any of the sort).
Try uninstalling and installing again:
```sh
npm -g uninstall generator-m-ionic
npm -g install generator-m-ionic
```
That should fix it.

**Comment by guruward** [comment]
sorry uninstalling and reinstalling, still the same error

**Comment by gruppjo** [comment]
Look into the installation folder of your node modules. Is yeoman-environment in the node_modules folder of generator-m-ionic? What happens if you run `npm install yeoman-environment` in the generator-m-ionic folder and then run yo m-ionic again?

**Comment by guruward** [comment]
yes I installed the yeoman-environment manually
its in the node_modules directory

but the error remains.

module.js:327
    throw err;
    ^

Error: Cannot find module 'yeoman-environment'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/router.js:9:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

On Jul 8, 2016, at 10:12 AM, Jonathan Grupp <notifications@github.com<mailto:notifications@github.com>> wrote:


Look into the installation folder of your node modules. Is yeoman-environment in the node_modules folder of generator-m-ionic? What happens if you run npm install yeoman-environment in the generator-m-ionic folder and then run yo m-ionic again?

**Comment by gruppjo** [comment]
This looks like a weird problem with your npm setup... Not sure how to help here.

**Comment by gruppjo** [comment]
closing due to inactivity. Please comment if you have updates.
